---
# tasks file for while_true_do.sys_update

- name: Manage Dependencies
  package:
    name: "{{ wtd_sys_update_dep_packages }}"
    state: "{{ wtd_sys_update_dep_packages_state }}"
  become: True
  tags:
    - update
    - package

- name: Update System Packages
  yum:
    name: "*"
    state: latest
    update_cache: True
  become: yes
  tags:
    - update
    - package

- name: Check System Reboot
  command: needs-restarting -r
  ignore_errors: True
  register: wtd_sys_update_reboot_check
  changed_when: wtd_sys_update_reboot_check.rc == 1 or
                wtd_sys_update_reboot_forced
  failed_when: wtd_sys_update_reboot_check.rc != 1 and
               wtd_sys_update_reboot_check.rc != 0
  become: True
  when: wtd_sys_update_reboot_enabled or
        wtd_sys_update_reboot_forced
  notify: Reboot System
  tags:
    - update
    - reboot
